# 01 Data Understanding

Week 1 notebook for exploring the credit risk dataset.

# AI-Powered Credit Risk Assessment & Smart Loan Recommendation System

## Business Problem

Banks receive thousands of loan applications every day. Approving loans for high-risk customers can lead to financial losses, while rejecting eligible customers can reduce business opportunities.

The objective of this project is to build a machine learning model that predicts whether a customer is eligible for a loan based on banking history and CIBIL information. Additionally, the project recommends an appropriate loan amount, repayment tenure, and provides business insights using exploratory data analysis.

## 1. Import Libraries

In [1]:
# Data Manipulation
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

print("Libraries imported successfully.")

Libraries imported successfully.

## 2. Load Datasets

In [2]:
import pandas as pd

internal_df = pd.read_excel("../data/raw/Internal_Bank_Dataset.xlsx")
external_df = pd.read_excel("../data/raw/External_Cibil_Dataset.xlsx")
unseen_df = pd.read_excel("../data/raw/Unseen_Dataset.xlsx")

print("Datasets loaded successfully.")

Datasets loaded successfully.

## 3. Inspect Dataset Shapes

In [3]:
print("Internal Dataset Shape :", internal_df.shape)
print("External Dataset Shape :", external_df.shape)
print("Unseen Dataset Shape   :", unseen_df.shape)

Internal Dataset Shape : (51336, 26)
External Dataset Shape : (51336, 62)
Unseen Dataset Shape   : (100, 42)

## 4. Preview Data

In [4]:
print("Internal Dataset")
display(internal_df.head())

print("External Dataset")
display(external_df.head())

print("Unseen Dataset")
display(unseen_df.head())

Internal Dataset

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,Total_TL_opened_L12M,Tot_TL_closed_L12M,pct_tl_open_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,Auto_TL,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,0,0,0.00,0.0,0,0,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,1,0,1.00,0.0,0,0,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,2,0,0.25,0.0,1,1,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,1,0,1.00,0.0,1,0,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,0,0,0.00,0.0,0,1,0,0,0,0,0,3,0,2,131,32

External Dataset

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,max_deliq_6mts,max_deliq_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,num_std_6mts,num_std_12mts,num_sub,num_sub_6mts,num_sub_12mts,num_dbt,num_dbt_6mts,num_dbt_12mts,num_lss,num_lss_6mts,num_lss_12mts,recent_level_of_deliq,tot_enq,CC_enq,CC_enq_L6m,CC_enq_L12m,PL_enq,PL_enq_L6m,PL_enq_L12m,time_since_recent_enq,enq_L12m,enq_L6m,enq_L3m,MARITALSTATUS,EDUCATION,AGE,GENDER,NETMONTHLYINCOME,Time_With_Curr_Empr,pct_of_active_TLs_ever,pct_opened_TLs_L6m_of_L12m,pct_currentBal_all_TL,CC_utilization,CC_Flag,PL_utilization,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,-99999,-99999,0,0,21,5,11,0,0,0,0,0,0,0,0,0,29,6,0,0,0,6,0,0,566,0,0,0,Married,12TH,48,M,51000,114,0.200,0.0,0.798,-99999.0,0,0.798,1,0.0,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,209,1,0,0,Single,GRADUATE,23,F,19000,50,1.000,0.0,0.370,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,25,25,0,0,10,5,10,0,0,0,0,0,0,0,0,0,25,4,0,0,0,0,0,0,587,0,0,0,Married,SSC,40,M,18,191,1.000,0.5,0.585,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,-99999,-99999,0,0,5,4,5,0,0,0,0,0,0,0,0,0,0,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,Married,SSC,34,M,10000,246,1.000,1.0,0.990,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,-99999,-99999,0,0,53,4,16,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3951,0,0,0,Married,POST-GRADUATE,48,M,15000,75,0.333,0.0,0.000,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

Unseen Dataset

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL,time_since_recent_payment,max_recent_level_of_deliq,num_deliq_6_12mts,num_times_60p_dpd,num_std_12mts,num_sub,num_sub_6mts,num_sub_12mts,num_dbt,num_dbt_12mts,num_lss,recent_level_of_deliq,CC_enq_L12m,PL_enq_L12m,time_since_recent_enq,enq_L3m,NETMONTHLYINCOME,Time_With_Curr_Empr,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,MARITALSTATUS,EDUCATION,GENDER,last_prod_enq2,first_prod_enq2
0,0.000,0.0,0,0.000,0,0,0,4,1,4,0,72,18,549,29,0,0,11,0,0,0,0,0,0,29,0,0,566,0,51000,114,0,1,0.000,0.0,1,0,Married,12TH,M,PL,PL
1,0.000,0.0,0,0.000,0,0,0,0,0,1,0,7,7,47,0,0,0,0,0,0,0,0,0,0,0,0,0,209,0,19000,50,0,0,0.000,0.0,0,0,Single,GRADUATE,F,ConsumerLoan,ConsumerLoan
2,0.125,0.0,0,0.000,1,0,0,0,2,6,0,47,2,302,25,8,0,10,0,0,0,0,0,0,25,0,0,587,0,18,191,0,0,0.000,0.0,1,0,Married,SSC,M,ConsumerLoan,others
3,0.000,0.0,0,0.000,0,0,0,0,3,0,2,131,32,583,0,0,0,16,0,0,0,0,0,0,0,0,0,3951,0,15000,75,0,0,0.000,0.0,0,0,Married,POST-GRADUATE,M,AL,AL
4,0.000,0.0,1,0.167,0,0,0,0,6,0,0,150,17,245,270,0,11,2,3,0,1,0,0,0,26,1,3,7,4,0,154,0,0,0.429,0.0,1,0,Married,12TH,M,ConsumerLoan,PL

## 5. Data Types

In [5]:
print("Internal Dataset")
display(internal_df.info())

print("External Dataset")
display(external_df.info())

print("Unseen Dataset")
display(unseen_df.info())

Internal Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PROSPECTID            51336 non-null  int64
 1   Total_TL              51336 non-null  int64
 2   Tot_Closed_TL         51336 non-null  int64
 3   Tot_Active_TL         51336 non-null  int64
 4   Total_TL_opened_L6M   51336 non-null  int64
 5   Tot_TL_closed_L6M     51336 non-null  int64
 6   pct_tl_open_L6M       51336 non-null  float64
 7   pct_tl_closed_L6M     51336 non-null  float64
 8   pct_active_tl         51336 non-null  float64
 9   pct_closed_tl         51336 non-null  float64
 10  Total_TL_opened_L12M  51336 non-null  int64
 11  Tot_TL_closed_L12M    51336 non-null  int64
 12  pct_tl_open_L12M      51336 non-null  float64
 13  pct_tl_closed_L12M    51336 non-null  float64
 14  Tot_Missed_Pmnt       51336 non-null  int64
 15  Auto_TL               51336 non-null  int64
 16  CC_TL                 51336 non-null  int64
 17  Consumer_TL           51336 non-null  int64
 18  Gold_TL               51336 non-null  int64
 19  Home_TL               51336 non-null  int64
 20  PL_TL                 51336 non-null  int64
 21  Secured_TL            51336 non-null  int64
 22  Unsecured_TL          51336 non-null  int64
 23  Other_TL              51336 non-null  int64
 24  Age_Oldest_TL         51336 non-null  int64
 25  Age_Newest_TL         51336 non-null  int64
dtypes: float64(6), int64(20)
memory usage: 10.2 MB

None

External Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 62 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PROSPECTID                    51336 non-null  int64
 1   time_since_recent_payment     51336 non-null  int64
 2   time_since_first_deliquency   51336 non-null  int64
 3   time_since_recent_deliquency  51336 non-null  int64
 4   num_times_delinquent          51336 non-null  int64
 5   max_delinquency_level         51336 non-null  int64
 6   max_recent_level_of_deliq     51336 non-null  int64
 7   num_deliq_6mts                51336 non-null  int64
 8   num_deliq_12mts               51336 non-null  int64
 9   num_deliq_6_12mts             51336 non-null  int64
 10  max_deliq_6mts                51336 non-null  int64
 11  max_deliq_12mts               51336 non-null  int64
 12  num_times_30p_dpd             51336 non-null  int64
 13  num_times_60p_dpd             51336 non-null  int64
 14  num_std                       51336 non-null  int64
 15  num_std_6mts                  51336 non-null  int64
 16  num_std_12mts                 51336 non-null  int64
 17  num_sub                       51336 non-null  int64
 18  num_sub_6mts                  51336 non-null  int64
 19  num_sub_12mts                 51336 non-null  int64
 20  num_dbt                       51336 non-null  int64
 21  num_dbt_6mts                  51336 non-null  int64
 22  num_dbt_12mts                 51336 non-null  int64
 23  num_lss                       51336 non-null  int64
 24  num_lss_6mts                  51336 non-null  int64
 25  num_lss_12mts                 51336 non-null  int64
 26  recent_level_of_deliq         51336 non-null  int64
 27  tot_enq                       51336 non-null  int64
 28  CC_enq                        51336 non-null  int64
 29  CC_enq_L6m                    51336 non-null  int64
 30  CC_enq_L12m                   51336 non-null  int64
 31  PL_enq                        51336 non-null  int64
 32  PL_enq_L6m                    51336 non-null  int64
 33  PL_enq_L12m                   51336 non-null  int64
 34  time_since_recent_enq         51336 non-null  int64
 35  enq_L12m                      51336 non-null  int64
 36  enq_L6m                       51336 non-null  int64
 37  enq_L3m                       51336 non-null  int64
 38  MARITALSTATUS                 51336 non-null  object
 39  EDUCATION                     51336 non-null  object
 40  AGE                           51336 non-null  int64
 41  GENDER                        51336 non-null  object
 42  NETMONTHLYINCOME              51336 non-null  int64
 43  Time_With_Curr_Empr           51336 non-null  int64
 44  pct_of_active_TLs_ever        51336 non-null  float64
 45  pct_opened_TLs_L6m_of_L12m    51336 non-null  float64
 46  pct_currentBal_all_TL         51336 non-null  float64
 47  CC_utilization                51336 non-null  float64
 48  CC_Flag                       51336 non-null  int64
 49  PL_utilization                51336 non-null  float64
 50  PL_Flag                       51336 non-null  int64
 51  pct_PL_enq_L6m_of_L12m        51336 non-null  float64
 52  pct_CC_enq_L6m_of_L12m        51336 non-null  float64
 53  pct_PL_enq_L6m_of_ever        51336 non-null  float64
 54  pct_CC_enq_L6m_of_ever        51336 non-null  float64
 55  max_unsec_exposure_inPct      51336 non-null  float64
 56  HL_Flag                       51336 non-null  int64
 57  GL_Flag                       51336 non-null  int64
 58  last_prod_enq2                51336 non-null  object
 59  first_prod_enq2               51336 non-null  object
 60  Credit_Score                  51336 non-null  int64
 61  Approved_Flag                 51336 non-null  object
dtypes: float64(10), int64(46), object(6)
memory usage: 24.3+ MB

None

Unseen Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 42 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   pct_tl_open_L6M            100 non-null    float64
 1   pct_tl_closed_L6M          100 non-null    float64
 2   Tot_TL_closed_L12M         100 non-null    int64
 3   pct_tl_closed_L12M         100 non-null    float64
 4   Tot_Missed_Pmnt            100 non-null    int64
 5   CC_TL                      100 non-null    int64
 6   Home_TL                    100 non-null    int64
 7   PL_TL                      100 non-null    int64
 8   Secured_TL                 100 non-null    int64
 9   Unsecured_TL               100 non-null    int64
 10  Other_TL                   100 non-null    int64
 11  Age_Oldest_TL              100 non-null    int64
 12  Age_Newest_TL              100 non-null    int64
 13  time_since_recent_payment  100 non-null    int64
 14  max_recent_level_of_deliq  100 non-null    int64
 15  num_deliq_6_12mts          100 non-null    int64
 16  num_times_60p_dpd          100 non-null    int64
 17  num_std_12mts              100 non-null    int64
 18  num_sub                    100 non-null    int64
 19  num_sub_6mts               100 non-null    int64
 20  num_sub_12mts              100 non-null    int64
 21  num_dbt                    100 non-null    int64
 22  num_dbt_12mts              100 non-null    int64
 23  num_lss                    100 non-null    int64
 24  recent_level_of_deliq      100 non-null    int64
 25  CC_enq_L12m                100 non-null    int64
 26  PL_enq_L12m                100 non-null    int64
 27  time_since_recent_enq      100 non-null    int64
 28  enq_L3m                    100 non-null    int64
 29  NETMONTHLYINCOME           100 non-null    int64
 30  Time_With_Curr_Empr        100 non-null    int64
 31  CC_Flag                    100 non-null    int64
 32  PL_Flag                    100 non-null    int64
 33  pct_PL_enq_L6m_of_ever     100 non-null    float64
 34  pct_CC_enq_L6m_of_ever     100 non-null    float64
 35  HL_Flag                    100 non-null    int64
 36  GL_Flag                    100 non-null    int64
 37  MARITALSTATUS              100 non-null    object
 38  EDUCATION                  100 non-null    object
 39  GENDER                     100 non-null    object
 40  last_prod_enq2             100 non-null    object
 41  first_prod_enq2            100 non-null    object
dtypes: float64(5), int64(32), object(5)
memory usage: 32.9+ KB

None

## 6. Missing Values

In [6]:
missing_internal = internal_df.isnull().sum().sort_values(ascending=False)
missing_external = external_df.isnull().sum().sort_values(ascending=False)
missing_unseen = unseen_df.isnull().sum().sort_values(ascending=False)

print("Internal Dataset")
display(missing_internal[missing_internal > 0])

print("External Dataset")
display(missing_external[missing_external > 0])

print("Unseen Dataset")
display(missing_unseen[missing_unseen > 0])

Internal Dataset

Series([], dtype: int64)

External Dataset

Series([], dtype: int64)

Unseen Dataset

Series([], dtype: int64)

## 7. Duplicate Records

In [7]:
print("Internal Duplicate Rows :", internal_df.duplicated().sum())

print("External Duplicate Rows :", external_df.duplicated().sum())

print("Unseen Duplicate Rows :", unseen_df.duplicated().sum())

Internal Duplicate Rows : 0

External Duplicate Rows : 0

Unseen Duplicate Rows : 0

## 8. Merge Datasets

In [8]:
merged_df = pd.merge(
    internal_df,
    external_df,
    on="PROSPECTID",
    how="inner"
)

print("Merged Dataset Shape :", merged_df.shape)

display(merged_df.head())

Merged Dataset Shape : (51336, 87)

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,Total_TL_opened_L12M,Tot_TL_closed_L12M,pct_tl_open_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,Auto_TL,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,max_deliq_6mts,max_deliq_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,num_std_6mts,num_std_12mts,num_sub,num_sub_6mts,num_sub_12mts,num_dbt,num_dbt_6mts,num_dbt_12mts,num_lss,num_lss_6mts,num_lss_12mts,recent_level_of_deliq,tot_enq,CC_enq,CC_enq_L6m,CC_enq_L12m,PL_enq,PL_enq_L6m,PL_enq_L12m,time_since_recent_enq,enq_L12m,enq_L6m,enq_L3m,MARITALSTATUS,EDUCATION,AGE,GENDER,NETMONTHLYINCOME,Time_With_Curr_Empr,pct_of_active_TLs_ever,pct_opened_TLs_L6m_of_L12m,pct_currentBal_all_TL,CC_utilization,CC_Flag,PL_utilization,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,0,0,0.00,0.0,0,0,0,0,1,0,4,1,4,0,72,18,549,35,15,11,29,29,0,0,0,-99999,-99999,0,0,21,5,11,0,0,0,0,0,0,0,0,0,29,6,0,0,0,6,0,0,566,0,0,0,Married,12TH,48,M,51000,114,0.200,0.0,0.798,-99999.0,0,0.798,1,0.0,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,1,0,1.00,0.0,0,0,0,1,0,0,0,0,1,0,7,7,47,-99999,-99999,0,-99999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,209,1,0,0,Single,GRADUATE,23,F,19000,50,1.000,0.0,0.370,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,2,0,0.25,0.0,1,1,0,6,1,0,0,2,6,0,47,2,302,11,3,9,25,25,1,9,8,25,25,0,0,10,5,10,0,0,0,0,0,0,0,0,0,25,4,0,0,0,0,0,0,587,0,0,0,Married,SSC,40,M,18,191,1.000,0.5,0.585,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,1,0,1.00,0.0,1,0,0,0,0,0,0,0,1,1,5,5,-99999,-99999,-99999,0,-99999,0,0,0,0,-99999,-99999,0,0,5,4,5,0,0,0,0,0,0,0,0,0,0,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,Married,SSC,34,M,10000,246,1.000,1.0,0.990,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,0,0,0.00,0.0,0,1,0,0,0,0,0,3,0,2,131,32,583,-99999,-99999,0,-99999,0,0,0,0,-99999,-99999,0,0,53,4,16,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3951,0,0,0,Married,POST-GRADUATE,48,M,15000,75,0.333,0.0,0.000,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

## 9. Statistical Summary

In [9]:
display(internal_df.describe())

display(external_df.describe())

display(unseen_df.describe())

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,Total_TL_opened_L12M,Tot_TL_closed_L12M,pct_tl_open_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,Auto_TL,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
count,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000
mean,25668.500000,4.858598,2.770415,2.088184,0.736754,0.428919,0.184574,0.089095,0.577542,0.422458,1.503701,0.736851,0.395184,0.149989,0.546751,0.593268,0.124981,1.136084,1.561847,0.070146,0.282511,2.844904,2.013694,1.089762,-32.575639,-62.149525
std,14819.571046,7.177116,5.941680,2.290774,1.296717,0.989972,0.297414,0.205635,0.379867,0.379867,2.119399,1.454120,0.391930,0.257267,1.085529,0.900585,0.505201,2.227997,5.376434,0.340861,0.858168,6.187177,3.198322,2.417496,2791.869609,2790.818622
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99999.000000,-99999.000000
25%,12834.750000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,4.000000
50%,25668.500000,2.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.556000,0.444000,1.000000,0.000000,0.333000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,33.000000,8.000000
75%,38502.250000,5.000000,3.000000,3.000000,1.000000,1.000000,0.308000,0.053000,1.000000,0.750000,2.000000,1.000000,0.750000,0.250000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,3.000000,2.000000,1.000000,64.000000,17.000000
max,51336.000000,235.000000,216.000000,47.000000,27.000000,19.000000,1.000000,1.000000,1.000000,1.000000,39.000000,39.000000,1.000000,1.000000,34.000000,27.000000,27.000000,41.000000,235.000000,10.000000,29.000000,235.000000,55.000000,80.000000,392.000000,392.000000

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,max_deliq_6mts,max_deliq_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,num_std_6mts,num_std_12mts,num_sub,num_sub_6mts,num_sub_12mts,num_dbt,num_dbt_6mts,num_dbt_12mts,num_lss,num_lss_6mts,num_lss_12mts,recent_level_of_deliq,tot_enq,CC_enq,CC_enq_L6m,CC_enq_L12m,PL_enq,PL_enq_L6m,PL_enq_L12m,time_since_recent_enq,enq_L12m,enq_L6m,enq_L3m,AGE,NETMONTHLYINCOME,Time_With_Curr_Empr,pct_of_active_TLs_ever,pct_opened_TLs_L6m_of_L12m,pct_currentBal_all_TL,CC_utilization,CC_Flag,PL_utilization,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,Credit_Score
count,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,5.133600e+04,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000
mean,25668.500000,-8129.961314,-70020.091320,-70022.375838,1.573749,-70003.987085,13.521953,0.184977,0.480053,0.295076,-25105.208587,-21092.727676,0.728884,0.426971,9.204671,1.484027,3.319444,0.062646,0.002435,0.009292,0.025947,0.001208,0.004130,0.015097,0.000974,0.002844,11.266090,-12308.234046,-12312.463866,-12312.734261,-12312.644869,-12311.878195,-12312.429270,-12312.209229,-12084.842099,-12310.233248,-12311.123987,-12311.784771,33.758532,2.642419e+04,110.707846,0.577542,0.302955,-139.416072,-92791.608990,0.089469,-86556.225194,0.167874,0.190414,0.065182,0.170492,0.056302,-45127.943635,0.271116,0.052887,679.859222
std,14819.571046,27749.328514,45823.312757,45819.820741,4.165012,45847.976100,53.336976,0.710240,1.522210,1.027471,43366.162767,40805.742595,2.762120,2.101404,21.308881,3.364581,7.518414,0.801218,0.091383,0.233403,0.635611,0.070331,0.179885,0.529730,0.075413,0.185349,46.100309,32860.363869,32858.778356,32858.677000,32858.710505,32858.997860,32858.791308,32858.873781,32946.916037,32859.614436,32859.280542,32859.032853,8.816364,2.002711e+04,76.046831,0.379867,0.406049,3742.613530,25861.225129,0.285423,34111.414750,0.373758,0.376218,0.235706,0.350209,0.213506,49795.784556,0.444540,0.223810,20.502764
min,1.000000,-99999.000000,-99999.000000,-99999.000000,0.000000,-99999.000000,0.000000,0.000000,0.000000,0.000000,-99999.000000,-99999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99999.000000,-99999.000000,-99999.000000,-99999.000000,-99999.000000,-99999.000000,-99999.000000,-99999.000000,-99999.000000,-99999.000000,-99999.000000,21.000000,0.000000e+00,0.000000,0.000000,0.000000,-99999.000000,-99999.000000,0.000000,-99999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99999.000000,0.000000,0.000000,469.000000
25%,12834.750000,46.000000,-99999.000000,-99999.000000,0.000000,-99999.000000,0.000000,0.000000,0.000000,0.000000,-99999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,27.000000,1.800000e+04,61.000000,0.250000,0.000000,0.083000,-99999.000000,0.000000,-99999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99999.000000,0.000000,0.000000,669.000000
50%,25668.500000,70.000000,-99999.000000,-99999.000000,0.000000,-99999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,45.000000,1.000000,1.000000,0.000000,32.000000,2.300000e+04,93.000000,0.556000,0.000000,0.617000,-99999.000000,0.000000,-99999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.333000,0.000000,0.000000,680.000000
75%,38502.250000,161.000000,8.000000,3.000000,1.000000,15.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,6.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,247.000000,3.000000,2.000000,1.000000,39.000000,3.000000e+04,131.000000,1.000000,0.643000,0.888000,-99999.000000,0.000000,-99999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.164250,1.000000,0.000000,691.000000
max,51336.000000,6065.000000,35.000000,35.000000,74.000000,900.000000,900.000000,12.000000,28.000000,20.000000,900.000000,900.000000,60.000000,52.000000,422.000000,60.000000,122.000000,42.000000,8.000000,20.000000,35.000000,6.000000,12.000000,72.000000,12.000000,30.000000,900.000000,176.000000,42.000000,17.000000,24.000000,46.000000,44.000000,44.000000,4768.000000,87.000000,66.000000,42.000000,77.000000,2.500000e+06,1020.000000,1.000000,1.000000,6327.500000,71.059000,1.000000,1.708000,1.000000,1.000000,1.000000,1.000000,1.000000,173800.000000,1.000000,1.000000,811.000000

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL,time_since_recent_payment,max_recent_level_of_deliq,num_deliq_6_12mts,num_times_60p_dpd,num_std_12mts,num_sub,num_sub_6mts,num_sub_12mts,num_dbt,num_dbt_12mts,num_lss,recent_level_of_deliq,CC_enq_L12m,PL_enq_L12m,time_since_recent_enq,enq_L3m,NETMONTHLYINCOME,Time_With_Curr_Empr,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag
count,100.000000,100.000000,100.00000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.0,100.00,100.00,100.0,100.0,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,0.191230,0.116210,0.71000,0.16822,0.410000,0.090000,0.040000,0.410000,2.330000,2.300000,1.140000,42.980000,13.000000,181.750000,22.800000,0.23000,0.410000,3.630000,0.080000,0.0,0.01,0.11,0.0,0.0,19.670000,0.170000,0.790000,287.920000,1.09000,25764.300000,108.330000,0.08000,0.230000,0.154610,0.093330,0.160000,0.030000
std,0.294655,0.253891,1.13079,0.27274,0.792579,0.320826,0.242878,1.005992,4.811718,2.544553,2.470104,36.271139,14.595558,270.985943,63.869659,0.90849,1.551116,7.473394,0.580491,0.0,0.10,1.10,0.0,0.0,58.377569,0.493493,1.793901,503.740607,1.83179,13707.266015,65.996029,0.27266,0.422953,0.335204,0.279607,0.368453,0.171447
min,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,1.000000,16.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.0,0.00,0.00,0.0,0.0,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,13.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,4.000000,54.750000,0.000000,0.00000,0.000000,0.000000,0.000000,0.0,0.00,0.00,0.0,0.0,0.000000,0.000000,0.000000,20.500000,0.00000,15875.000000,60.750000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,1.500000,0.000000,39.000000,8.000000,75.500000,0.000000,0.00000,0.000000,0.000000,0.000000,0.0,0.00,0.00,0.0,0.0,0.000000,0.000000,0.000000,148.500000,0.00000,24000.000000,101.500000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.343500,0.091000,1.00000,0.25000,0.250000,0.000000,0.000000,0.000000,2.000000,3.000000,1.000000,59.000000,14.500000,143.000000,15.250000,0.00000,0.000000,5.000000,0.000000,0.0,0.00,0.00,0.0,0.0,15.250000,0.000000,1.000000,298.500000,1.00000,30000.000000,130.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,5.00000,1.00000,3.000000,2.000000,2.000000,7.000000,35.000000,10.000000,16.000000,191.000000,76.000000,1492.000000,478.000000,8.00000,11.000000,43.000000,5.000000,0.0,1.00,11.00,0.0,0.0,478.000000,3.000000,13.000000,3951.000000,10.00000,65000.000000,306.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000

## 10. Save the Processed Dataset

In [10]:
merged_df.to_csv("../data/processed/merged_dataset.csv", index=False)

print("Merged dataset saved successfully.")

Merged dataset saved successfully.